# Build version format
version: 1.0.{build}-{branch}

# Test against this version of Node.js
environment:
  matrix:
  # node.js
  - nodejs_version: "0.12"

matrix:
  fast_finish: true     # set this flag to immediately finish build once one of the jobs fails
  
install:
  # install modules
  - npm install -g gulp
  - npm install
  
build_script:
  - gulp release

# to disable deployment
deploy: off

notifications:
  # Email
  - provider: Email
    to:
      - windygrid@cityofchicago.org
      - developers@cityofchicago.org
    on_build_status_changed: true
